
name: 'SemVer Tag on Main Merge'
on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  pull-requests: read
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  semver-tag:
    name: 'Tag Repository with SemVer'
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'skip-release') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse the SemVer label
        id: label
        uses: UKHomeOffice/match-label-action@489dd452bec62fe80380c694af4450f48fb12af3
        with:
          labels: minor,major,patch
          mode: singular

      - name: Calculate SemVer value
        id: calculate
        uses: UKHomeOffice/semver-calculate-action@bb1b9e616bdd29cfe7a1e82c533e4eb6a86687d8
        with:
          increment: ${{ steps.label.outputs.matchedLabels }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Repository
        uses: UKHomeOffice/semver-tag-action@51e12c5946815d7f794100d58c9b39d33a72aa04
        with:
          tag: ${{ steps.calculate.outputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}